# Prometheus configuration for MedusaXD Bot monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MongoDB monitoring (if mongodb_exporter is added)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  # Redis monitoring (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Bot application metrics (if metrics endpoint is added)
  - job_name: 'medusaxd-bot'
    static_configs:
      - targets: ['medusaxd-bot:8000']
    scrape_interval: 30s
    metrics_path: '/metrics'
